//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteorEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeteorContentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeteorContentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeteorEngine.MeteorContentResource", typeof(MeteorContentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ball {
            get {
                object obj = ResourceManager.GetObject("ball", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] blur {
            get {
                object obj = ResourceManager.GetObject("blur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] clearGBuffer {
            get {
                object obj = ResourceManager.GetObject("clearGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] combination {
            get {
                object obj = ResourceManager.GetObject("combination", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] defaultFont {
            get {
                object obj = ResourceManager.GetObject("defaultFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] depth {
            get {
                object obj = ResourceManager.GetObject("depth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] directionalLight {
            get {
                object obj = ResourceManager.GetObject("directionalLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fxaa {
            get {
                object obj = ResourceManager.GetObject("fxaa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] null_color {
            get {
                object obj = ResourceManager.GetObject("null_color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] null_normal {
            get {
                object obj = ResourceManager.GetObject("null_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] null_specular {
            get {
                object obj = ResourceManager.GetObject("null_specular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pointLight {
            get {
                object obj = ResourceManager.GetObject("pointLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] random {
            get {
                object obj = ResourceManager.GetObject("random", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] renderGBuffer {
            get {
                object obj = ResourceManager.GetObject("renderGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] seattle {
            get {
                object obj = ResourceManager.GetObject("seattle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] segoeUI {
            get {
                object obj = ResourceManager.GetObject("segoeUI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] skyblue_cube {
            get {
                object obj = ResourceManager.GetObject("skyblue_cube", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ssao {
            get {
                object obj = ResourceManager.GetObject("ssao", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
